using Filmposter.Domain.Common;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Filmposter.Domain.Entities.Users
{
    public class UserPayments : BaseEntityGuid
    {
        public Guid UserId { get; set; }
        public virtual Users User { get; set; }


        public double Amount { get; set; }
        public double Discount { get; set; }
        public string? DiscountReason { get; set; }
        public bool Returned { get; set; } // {true} => the money is retunred by admnin 


        // BANK Properties
        public string? Bank_InvoiceNumber { get; set; }
        // the fourth part of Guid.Id (like: 00b43bdc2e74 from d5233318-7654-4d82-a422-00b43bdc2e74)
        // the above value will be sent to the bank and generated by us
        public string? Bank_PaymentNumber { get; set; } // this value will be generated by bank and retruned!
        public byte Bank_Status { get; set; } // {0}:fail {1}:success => BankStatusConstants.cs
        public string? Bank_Message { get; set; } // the {message} is retruend from the request
    }
}
